name: StarRocks UT
trigger:
  change:
    types: [ submit, create, push ]

jobs:
  ut-fe:
    image: hub.byted.org/compile/starrocks-3.2:fba559edda9ec6ddb27bc557758bba1d
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: fe
        commands:
          - mkdir -p /root/.m2/
          - cp .codebase/settings.xml /root/.m2/
          - sh run-fe-ut.sh
  ut-be:
    image: hub.byted.org/compile/starrocks-3.2:fba559edda9ec6ddb27bc557758bba1d
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: be
        commands:
          # -j 12 to avoid kill by system while linking
          - sh run-be-ut.sh --use-staros -j 12


  starrocks_format_sdk:
    image:  hub.byted.org/compile/emr-starrocks-lh-3.1-builder:412c9075707bcf65af9f7f7a8f53f506
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: run-sr-format-sdk-test
        commands:
          - mkdir -p /root/.m2/
          - cp .codebase/settings.xml /root/.m2/
          - sh .codebase/run-sr-format-sdk-test.sh


